backend:
  name: github
  repo: dahemar/coranovoa
  branch: main
  site_domain: coranovoa.netlify.app
  auth_endpoint: https://github.com/login/oauth/authorize
  client_id: Ov23li9Bd9fudYzANB0g

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Páginas"
    files:
      - name: "bio"
        label: "Bio"
        file: "bio.html"
        fields:
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Texto Bio (Galego)", name: "bio_text_gl", widget: "text"}
          - {label: "Texto Bio (Español)", name: "bio_text_es", widget: "text"}
          - {label: "Texto Bio (English)", name: "bio_text_en", widget: "text"}
          - {label: "Obradoiros (Galego)", name: "workshops_text_gl", widget: "text"}
          - {label: "Obradoiros (Español)", name: "workshops_text_es", widget: "text"}
          - {label: "Obradoiros (English)", name: "workshops_text_en", widget: "text"}
          - {label: "Exposicións (Galego)", name: "exhibitions_text_gl", widget: "text"}
          - {label: "Exposicións (Español)", name: "exhibitions_text_es", widget: "text"}
          - {label: "Exposicións (English)", name: "exhibitions_text_en", widget: "text"}

      - name: "aldan"
        label: "Aldán"
        file: "aldan.html"
        fields:
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Texto (Galego)", name: "text_gl", widget: "text"}
          - {label: "Texto (Español)", name: "text_es", widget: "text"}
          - {label: "Texto (English)", name: "text_en", widget: "text"}

      - name: "curaduria"
        label: "Curaduría"
        file: "curaduria.html"
        fields:
          - {label: "Título", name: "title", widget: "string"}
          - label: "Proyectos (Galego)"
            name: "projects_gl"
            widget: "list"
            fields:
              - {label: "Título", name: "title", widget: "string"}
              - {label: "Descripción", name: "description", widget: "text"}
              - {label: "Imagen", name: "image", widget: "image"}
          - label: "Proyectos (Español)"
            name: "projects_es"
            widget: "list"
            fields:
              - {label: "Título", name: "title", widget: "string"}
              - {label: "Descripción", name: "description", widget: "text"}
              - {label: "Imagen", name: "image", widget: "image"}
          - label: "Proyectos (English)"
            name: "projects_en"
            widget: "list"
            fields:
              - {label: "Título", name: "title", widget: "string"}
              - {label: "Descripción", name: "description", widget: "text"}
              - {label: "Imagen", name: "image", widget: "image"}

      - name: "obra"
        label: "Obra"
        file: "obra.html"
        fields:
          - {label: "Título", name: "title", widget: "string"}
          - label: "Obras"
            name: "works"
            widget: "list"
            fields:
              - {label: "Título", name: "title", widget: "string"}
              - {label: "Año", name: "year", widget: "string"}
              - {label: "Imagen", name: "image", widget: "image"}
              - {label: "Descripción (Galego)", name: "description_gl", widget: "text"}
              - {label: "Descripción (Español)", name: "description_es", widget: "text"}
              - {label: "Descripción (English)", name: "description_en", widget: "text"}

      - name: "contacto"
        label: "Contacto"
        file: "contacto.html"
        fields:
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Instagram", name: "instagram", widget: "string"} 