backend:
  name: "auth0"
  branch: "main"

local_backend: true  # Optional: enables local development

# Auth0 configuration should be in your index.html, not here in config.yml
# (which you already have correctly set up)

media_library:
  name: "uploadcare"
  config:
    publicKey: "your-uploadcare-public-key"  # Replace with your actual Uploadcare public key

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
